export const projects = [
  {
    title: 'Collocated VR',
    description: "This project is focused on writing a multiplayer Unity application. My goals was to integrate different technologies into a scene and create a smart space that is able to track and display any content on any of these devices. In our case, the system contained two devices which were two Oculus Quest 2 on par with Optitrack. This system could serve as a sandbox application in order to test new types of interactions that could happen between two co-located users in the virtual world.",
      image: '/images/Internship - Project Image.png',
      tags: ['Unity', 'VR', 'C#', 'Visual Studio', 'Optitrack'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'SocialVR',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/SocialVR - Project Image.jpg',
    tags: ['Unity', 'VR', 'C#', 'OpenCV'],
    source: '/SocialVR',
    visit: 'https://www.youtube.com/playlist?list=PLDZktaCsdtVd3d242j5bLonuyc_trXKvB',
    id: 1,
  },
  {
    title: 'VR Mechanic',
    description: "This is a VR project with the purpose of creating a VR Training application. In our application the logical skills of the user are put into test, where he/she has to assemble and reassemble a motor engine",
      image: '/images/VR Engine/VR Engine - Project Image.png',
      tags: ['Unity', 'VR', 'C#'],
    source: '/VRMechanic',
    visit: 'https://www.youtube.com/playlist?list=PLDZktaCsdtVdNabzgn6O14y3jrMjLKEz8',
    id: 2,
  },
  {
    title: 'Stabbing Post-its VR',
    description: "This project was created on par with a designer and the main concept was to conceptualize how post-its would be integrated into a VR application",
    image: '/images/Stabbing Post-it VR/Stabbing Post-its - Project Image.jpg',
    tags: ['Unity', 'VR', 'C#'],
    source: '/StabbingPostitsVR',
    visit: 'https://www.youtube.com/watch?v=yf8Abz3wlqI',
    id: 3,
  },{
    title: 'ARcher',
    description: "This is an AR game that transforms a game into another. A card game into a platformer into an unconventional way",
    image: '/images/ARcher/ARcher - Project Image.jpg',
    tags: ['Unity', 'AR', 'C#', 'Mobile'],
    source: '/ARcher',
    visit: 'https://www.youtube.com/playlist?list=PLDZktaCsdtVc7qyGFGxfA7N8yqFrGlApn',
    id: 4},
    {
    title: 'VR Haptic Glove - Magos',
    description: "When I worked as a developer at Magos, my main task was to create an API inder to integrate a custom VR Haptic glove into Unity.",
    image: '/images/VR Haptic Glove - Magos/Magos - Project Image.jpeg',
    tags: ['Unity', 'VR', 'C#'],
    source: '/HapticGloveVR',
    visit: 'https://www.youtube.com/playlist?list=PLDZktaCsdtVc7qyGFGxfA7N8yqFrGlApn',
    id: 5},
    {
    title: 'Fruit Slicer VR',
    description: "This is an AR game that transforms a game into another. A card game into a platformer into an unconventional way",
    image: '/images/ARcher/ARcher - Project Image.jpg',
    tags: ['Unity', 'AR', 'C#', 'Mobile'],
    source: '/ARcher',
    visit: 'https://www.youtube.com/playlist?list=PLDZktaCsdtVc7qyGFGxfA7N8yqFrGlApn',
    id: 6},
    {
    title: 'Superman VR',
    description: "This is an AR game that transforms a game into another. A card game into a platformer into an unconventional way",
    image: '/images/ARcher/ARcher - Project Image.jpg',
    tags: ['Unity', 'AR', 'C#', 'Mobile'],
    source: '/ARcher',
    visit: 'https://www.youtube.com/playlist?list=PLDZktaCsdtVc7qyGFGxfA7N8yqFrGlApn',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];