export const projects = [
  {
    title: 'Collocated VR',
    description: "This project was created on par with IP Paris as my internship. The goal of this project was to combine multiple XR devices into one smart space. The current implentation involves the Optitrack and the Oculus Quest 2",
      image: '/images/Internship - Project Image.png',
      tags: ['Unity', 'VR', 'C#', 'Optitrack'],
    source: '/CollocatedVR',
    visit: 'https://youtube.com/playlist?list=PLDZktaCsdtVeMaMwjg-SlbdHiLIk7Q9I6
    id: 0,
  },
  {
    title: 'SocialVR',
    description:"The main objective of this project is to combine VR with the real world. This is done through a new kind of selfie that enables users to take picture and blend their environments in two ways. ",
    image: '/images/SocialVR - Project Image.jpg',
    tags: ['Unity', 'VR', 'C#', 'OpenCV'],
    source: '/SocialVR',
    visit: 'https://youtube.com/playlist?list=PLDZktaCsdtVd3d242j5bLonuyc_trXKvB',
    id: 1,
  },
  {
    title: 'VR Mechanic',
    description: "This is a VR project with the purpose of creating a VR Training application. In our application the logical skills of the user are put into test, where he/she has to assemble and reassemble a motor engine",
      image: '/images/VR Engine/VR Engine - Project Image.png',
      tags: ['Unity', 'VR', 'C#'],
    source: '/VRMechanic',
    visit: 'https://youtube.com/playlist?list=PLDZktaCsdtVdNabzgn6O14y3jrMjLKEz8',
    id: 2,
  },
  {
    title: 'Stabbing Post-its VR',
    description: "This project was created on par with a designer and the main concept was to conceptualize how post-its would be integrated into a VR application",
    image: '/images/Stabbing Post-it VR/Stabbing Post-its - Project Image.jpg',
    tags: ['Unity', 'VR', 'C#'],
    source: '/StabbingPostitsVR',
    visit: 'https://www.youtube.com/watch?v=yf8Abz3wlqI',
    id: 3,
  },{
    title: 'ARcher',
    description: "This is an AR game that transforms a game into another. A card game into a platformer into an unconventional way",
    image: '/images/ARcher/ARcher - Project Image.jpg',
    tags: ['Unity', 'AR', 'C#', 'Mobile'],
    source: '/ARcher',
    visit: 'https://youtube.com/playlist?list=PLDZktaCsdtVc7qyGFGxfA7N8yqFrGlApn',
    id: 4},
    {
    title: 'VR Haptic Glove - Magos',
    description: "When I worked as a developer at Magos, my main task was to create an API in order to integrate a custom VR Haptic glove into Unity.",
    image: '/images/VR Haptic Glove - Magos/Magos - Project Image.jpeg',
    tags: ['Unity', 'VR', 'C#', 'Humanoid'],
    source: '/HapticGloveVR',
    visit: 'https://youtube.com/playlist?list=PLDZktaCsdtVdZnlw50DmnNaHHUWVLYQM_',
    id: 5},
    {
    title: 'Fruit Slicer VR',
    description: "I created this project on par with IP Paris for a paper that is trying to explore the harmful concequences of VR and also its boundaries",
    image: '/images/FruitSlicer VR/FruitSlicer VR - Project Image.png',
    tags: ['Unity', 'VR', 'C#', 'Photon'],
    source: '/FruitSlicerVR',
    visit: 'https://www.youtube.com/watch?v=0ph16W51JTA',
    id: 6},
    {
    title: 'Pet Endless Runner',
    description: "This is one of my first Unity project and was created for a website. This is an endless runner where players can upload their scores in a online leaderboard",
    image: '/images/Pet Endless Runner/Pet Endless Runner - Project Image.jpg',
    tags: ['Unity', 'C#', 'WebGL'],
    source: '/PetEndlessRunner',
    visit: 'https://www.youtube.com/watch?v=GcGeCE7Blo4',
    id: 7},
    {
    title: 'Superman VR',
    description: "This is a VR project I created in order to experiment and test the functionallities of the Oculus Quest hand tracking",
    image: '/images/Superman VR/Superman VR - Project Image.jpg',
    tags: ['Unity', 'C#', 'VR', 'Hand Tracking'],
    source: '/SupermanVR',
    visit: 'https://www.youtube.com/watch?v=kOAVx5cbF8Q',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Diploma thesis in Unity', },
  { year: 2018, text: 'Android developer in Ingredio', },
  { year: 2019, text: 'Unity/Android developer in COMIC', },
  { year: 2020, text: 'Unity developer at COMIC & MAGOS', },
  { year: 2021, text: 'Master & Internship in IP Paris', },
];